import Head from "next/head";
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'

import { Poppins } from '@next/font/google';

export const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
     <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
